site_name: Signal
site_url: https://astrocorp.net
repo_url: https://github.com/astrocorp42/signal

site_dir: dist
docs_dir: pages

google_analytics:
  - 'UA-123569541-1'
  - 'auto'

theme:
  name: null
  custom_dir: 'themes/mkdocs-material/material'
  language: en
  feature:
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

nav:
  - index.md
